snc_redis:
    clients:
        monolog:
            type: predis
            alias: monolog
            dsn: '%env(REDIS_URL_EVENTS)%'
            logging: false
            options:
                connection_persistent: true
    monolog:
        client: monolog
        key: monolog
# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
