monolog:
    channels: ['customEvent']
    handlers:
        redis:
            type: service
            id: snc_redis.monolog.handler
            level: debug
            channels: [ "customEvent" ]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
